import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/theme/theme.css";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CoopLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar></Navbar>
          {children}
        </body>
      </html>
    </PrimeReactProvider>
  );
}
